# Generated by Django 3.1 on 2021-01-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0002_auto_20210119_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='prod_state',
            field=models.CharField(choices=[('removed', 'removed'), ('cart', 'cart'), ('checkout', 'checkout'),('payment', 'payment'), ('received', 'received'), ('failed', 'failed')], default='removed', max_length=15),
        ),
        migrations.AddField(
            model_name='userrider',
            name='rider_state',
            field=models.CharField(choices=[('toShop', 'toShop'), ('pickedup', 'pickedup'), ('received', 'received'), ('failed', 'failed')], default='toShop', max_length=15),
        ),
    ]
