# Generated by Django 3.1 on 2021-01-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserNo', models.CharField(max_length=15)),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('preferred_name', models.CharField(max_length=128)),
                ('address', models.TextField(max_length=2000)),
                ('City', models.CharField(max_length=15)),
                ('Province', models.CharField(max_length=15)),
                ('Country', models.CharField(max_length=15)),
                ('ContactNo', models.CharField(max_length=15)),
                ('SecondaryContactNo', models.CharField(max_length=15)),
                ('active_buyer', models.BooleanField(max_length=15)),
                ('Username', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
