# Generated by Django 3.1 on 2021-01-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('associates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('product_description', models.TextField(max_length=2000)),
                ('product_type', models.CharField(choices=[('raw', 'raw'), ('vegetable', 'vegetable'), ('Packed Goods', 'Packed Goods'), ('Essentials', 'Essentials'), ('Cooked Goods', 'Cooked Goods')], default='Project-based', max_length=15)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('store', models.ManyToManyField(through='associates.StoreProduct', to='store.Store')),
                ('user', models.ManyToManyField(through='associates.UserProduct', to='userForm.Users')),
            ],
        ),
    ]
