# Generated by Django 3.1 on 2021-01-19 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerNo', models.CharField(max_length=15)),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('preferred_name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=2000)),
                ('City', models.CharField(max_length=15)),
                ('Province', models.CharField(max_length=15)),
                ('Country', models.CharField(max_length=15)),
                ('ContactNo', models.CharField(max_length=15)),
                ('SecondaryContactNo', models.CharField(max_length=15)),
                ('active_seller', models.BooleanField(max_length=15)),
                ('Username', models.EmailField(blank=True, max_length=30, null=True, unique=True)),
                ('Password', models.CharField(max_length=30)),
                ('storeNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
